### ISSUE TITLE
DE01 : Chiffrement mots de passe

### ISSUE THREAD

**Issue by Titouan826** [KeligRimpot/AppliFrais#3]
On va crypter les mdps qui sont pour l'instant stockés en clair avec un algorythme de hachage.

**Comment by Titouan826** [comment]
Je vais utiliser Argon2id comme algo de hash après avoir regardé les recommendations de l'OWASP. C'est plus sécurisé.

**Comment by Titouan826** [comment]
Ca y est, la première modification est terminée ! 
Les mdps ne sont plus stockés en clair. A la place, on stocke leur hash avec ARGON2ID dans la bdd. 
J'ai modifié et documenté mon code. Entre autre, il a fallu modifier la requête SQL et le PDO, et la fonction getInfosVisiteur()

https://github.com/KeligRimpot/AppliFrais/blob/b564e24d94d259a9515668f22b6fbfaefa4fe015/www/include/class.pdogsb.inc.php#L46-L55

https://github.com/KeligRimpot/AppliFrais/blob/b564e24d94d259a9515668f22b6fbfaefa4fe015/www/controleurs/c_connexion.php#L11-L34

**Comment by KeligRimpot** [comment]
Je n'arrive pas à me connecter...

**Comment by Titouan826** [comment]
C'est normal ! C'est un oubli de ma part :
J'ai rajouter un script qui remplace les mdps en clair par des hashs ARGON2ID dans la bdd.
Il faut que tu ouvres un cmd et tapes la commande suivante : 
"php hash_mdps_bdd.php"
Ensuite, tu pourras te connecter.
